blank_issues_enabled: false
contact_links:
  - name: Pregunta general
    url: https://github.com/JorkLucas03/StudyFlow/discussions
    about: Usa discusiones para preguntas que no sean errores o mejoras concretas.
